/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
import model.Student;
import model.Subject;
import service.SubjectService;
import static view.QuanLyMonHoc.setDataTableSubject;


/**
 *
 * @author linh
 */
public class AddSubjectFormDialog extends javax.swing.JDialog {
    private SubjectService subjectService;
//    private DefaultTableModel defaultTableModel;
    /**
     * Creates new form AddStudentFormDialog
     */
    public AddSubjectFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        subjectService = new SubjectService();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTinchi = new javax.swing.JTextField();
        cbMaNganh = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhập thông tin môn học");
        setMinimumSize(new java.awt.Dimension(420, 350));
        getContentPane().setLayout(null);

        jLabel1.setText(" Mã ngành:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 66, 80, 14);

        jLabel2.setText("Tên môn học:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 109, 90, 14);
        getContentPane().add(txtten);
        txtten.setBounds(108, 96, 282, 30);

        jLabel3.setText("Số tín chỉ:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 150, 70, 14);
        getContentPane().add(txtTinchi);
        txtTinchi.setBounds(108, 140, 280, 30);

        cbMaNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNTT", "ATTT", "DT", "DTVT", "CNDPT", "MAR", "QTKD", "KT", "TMDT", "CB", " " }));
        getContentPane().add(cbMaNganh);
        cbMaNganh.setBounds(108, 53, 282, 30);

        btnRefresh.setBackground(new java.awt.Color(255, 0, 51));
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh);
        btnRefresh.setBounds(10, 250, 73, 30);

        btnSave.setBackground(new java.awt.Color(255, 0, 51));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(317, 250, 73, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-20, -20, 470, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        cbMaNganh.setSelectedIndex(0);
        txtten.setText("");
        txtTinchi.setText("0");
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(checkDL()){
            String ma = cbMaNganh.getSelectedItem().toString();
            String tenMH = txtten.getText();
            int tinchi = Integer.valueOf(txtTinchi.getText());
            Subject sub = new Subject(ma,tenMH,tinchi);
            subjectService.addSubject(sub);
            setDataTableSubject(subjectService.getAllSubjects());
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddSubjectFormDialog dialog = new AddSubjectFormDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbMaNganh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtTinchi;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
    private boolean checkDL() {
        if(txtten.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Tên môn học rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false; 
        } else if(!Pattern.matches("\\d{1}$", txtTinchi.getText())){
            JOptionPane.showMessageDialog(this, "Số tín chỉ nhỏ hơn 10", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }else return true;
    }
    
}
