/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
import model.Student;
import service.StudentService;
import static view.QuanLySinhVien.setDataTableStudent;


/**
 *
 * @author Duc Thanh
 */
public class AddStudentFormDialog extends javax.swing.JDialog {
    private StudentService studentService;
//    private DefaultTableModel defaultTableModel;
    /**
     * Creates new form AddStudentFormDialog
     */
    public AddStudentFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        studentService = new StudentService();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCMT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbGioiTinh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtDiemXetTuyen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbNganhHoc = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhập thông tin sinh viên");
        setMinimumSize(new java.awt.Dimension(420, 440));
        getContentPane().setLayout(null);

        jLabel1.setText("Họ tên:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 26, 50, 14);
        getContentPane().add(txtName);
        txtName.setBounds(94, 13, 296, 30);

        jLabel2.setText("Ngày sinh:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 64, 60, 14);
        getContentPane().add(txtNgaySinh);
        txtNgaySinh.setBounds(94, 51, 296, 30);

        jLabel3.setText("Số CMT/CCCD:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 102, 110, 14);
        getContentPane().add(txtCMT);
        txtCMT.setBounds(94, 89, 296, 30);

        jLabel4.setText("Giới tính:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 60, 14);

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        getContentPane().add(cbGioiTinh);
        cbGioiTinh.setBounds(94, 127, 60, 30);

        jLabel5.setText("Điểm xét tuyển:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 178, 110, 14);
        getContentPane().add(txtDiemXetTuyen);
        txtDiemXetTuyen.setBounds(94, 165, 296, 30);

        jLabel6.setText("Email:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 216, 50, 14);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(94, 203, 296, 30);

        jLabel7.setText("Địa chỉ:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 254, 40, 14);
        getContentPane().add(txtDiaChi);
        txtDiaChi.setBounds(94, 241, 296, 30);

        jLabel8.setText("SĐT:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 292, 50, 14);
        getContentPane().add(txtSoDienThoai);
        txtSoDienThoai.setBounds(94, 279, 296, 30);

        jLabel9.setText("Ngành học:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 327, 80, 14);

        cbNganhHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công Nghệ Thông Tin", "An Toàn Thông Tin", "Công Nghệ Kỹ Thuật Điện-Điện Tử", "Kỹ Thuật Điện Tử Viễn Thông", "Công Nghệ Đa Phương Tiện", "Marketing", "Quản Trị Kinh Doanh", "Kế Toán", " " }));
        getContentPane().add(cbNganhHoc);
        cbNganhHoc.setBounds(94, 317, 296, 30);

        btnRefresh.setBackground(new java.awt.Color(255, 0, 51));
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh);
        btnRefresh.setBounds(10, 358, 73, 30);

        btnSave.setBackground(new java.awt.Color(255, 0, 51));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(317, 358, 73, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add1.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-10, 0, 470, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtNgaySinh.setText("");
        txtCMT.setText("");
        cbGioiTinh.setSelectedIndex(0);
        txtDiemXetTuyen.setText("");
        txtEmail.setText("");
        txtDiaChi.setText("");
        txtSoDienThoai.setText("");
        cbNganhHoc.setSelectedIndex(0);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(checkDL()){
            String name = txtName.getText();
            String ns = txtNgaySinh.getText();
            String cmt = txtCMT.getText();
            String gioiTinh = cbGioiTinh.getSelectedItem().toString();
            Float diemXT = Float.valueOf(txtDiemXetTuyen.getText());
            String email = txtEmail.getText();
            String diaChi = txtDiaChi.getText();
            String sdt = txtSoDienThoai.getText();
            String nganhHoc = cbNganhHoc.getSelectedItem().toString();
            boolean hocBong = false;
            if(diemXT >= 25){
                hocBong = true;
            }
            Student std = new Student(name,ns,cmt,gioiTinh,diemXT,email,diaChi,sdt,nganhHoc,hocBong);
            studentService.addStudent(std);
            setDataTableStudent(studentService.getAllStudent());
//            System.exit(0);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddStudentFormDialog dialog = new AddStudentFormDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbNganhHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCMT;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiemXetTuyen;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoDienThoai;
    // End of variables declaration//GEN-END:variables
    private boolean checkDL() {
        if(!Pattern.matches("^([a-z A-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ])[a-z A-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]+$", txtName.getText())){
            JOptionPane.showMessageDialog(this, "Họ và tên chỉ có chữ cái", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(!Pattern.matches("^\\d{4}-((0[1-9]{1})|(1[0-2]{1}))-((0[1-9]{1})|([1-2]{1}[0-9]{1})|(3(0|1)))$", txtNgaySinh.getText())){
            JOptionPane.showMessageDialog(this, "Ngày sinh năm-tháng-ngày (yyyy-mm-dd)", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(!Pattern.matches("\\d{12}$", txtCMT.getText())){
            JOptionPane.showMessageDialog(this, "Chứng minh thư chỉ có 12 chữ số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(!Pattern.matches("(^-)*\\d+(.\\d+)*", txtDiemXetTuyen.getText())){
            JOptionPane.showMessageDialog(this, "Điểm xét tuyển sai định dạnh", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;                  
        }else if(!Pattern.matches("^[a-zA-z0-9_-]+(@gmail.com)$", txtEmail.getText())){
            JOptionPane.showMessageDialog(this, "Email có dạng x..x@gmail.com", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(txtDiaChi.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Địa chỉ chưa tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;            
        }else if(!Pattern.matches("^(0)\\d{9}$", txtSoDienThoai.getText())){
            JOptionPane.showMessageDialog(this, "SĐT bắt đầu bằng số 0 và có 10 chữ số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false; 
        }else return true;
    }
    
}
