/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Frame;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Student;
import service.StudentService;

/**
 *
 * @author Admin
 */
public class DangKySV extends javax.swing.JFrame {
    private StudentService studentService;
    /**
     * Creates new form DangNhapSV
     */
    public DangKySV(java.awt.Frame parent, boolean modal) {
        super();
        initComponents();
        setLocationRelativeTo(this);
        studentService = new StudentService();
        setResizable(false);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        jname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtcmt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jpass = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jpass1 = new javax.swing.JLabel();
        txtpass1 = new javax.swing.JPasswordField();
        btnsingin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng ký tài khoản");
        setMaximumSize(new java.awt.Dimension(400, 350));
        setMinimumSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        txtTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(255, 51, 51));
        txtTitle.setText("Nhập Thông Tin Đăng Ký");
        getContentPane().add(txtTitle);
        txtTitle.setBounds(106, 14, 190, 30);

        jname.setText("Họ Tên:");
        getContentPane().add(jname);
        jname.setBounds(10, 65, 60, 14);
        getContentPane().add(txtname);
        txtname.setBounds(123, 52, 218, 30);

        jLabel1.setText("CMT/CCCD:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 106, 110, 14);

        txtcmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcmtActionPerformed(evt);
            }
        });
        getContentPane().add(txtcmt);
        txtcmt.setBounds(123, 93, 218, 30);

        jLabel2.setText("Email:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 147, 60, 14);

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail);
        txtemail.setBounds(123, 134, 218, 30);

        jpass.setText("Mật khẩu:");
        getContentPane().add(jpass);
        jpass.setBounds(10, 185, 70, 14);
        getContentPane().add(txtpass);
        txtpass.setBounds(123, 172, 218, 30);

        jpass1.setText("Nhập lại mật khẩu");
        getContentPane().add(jpass1);
        jpass1.setBounds(10, 226, 100, 14);
        getContentPane().add(txtpass1);
        txtpass1.setBounds(123, 213, 218, 30);

        btnsingin.setBackground(new java.awt.Color(255, 0, 51));
        btnsingin.setForeground(new java.awt.Color(255, 255, 255));
        btnsingin.setText("Đăng ký tài khoản");
        btnsingin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinginActionPerformed(evt);
            }
        });
        getContentPane().add(btnsingin);
        btnsingin.setBounds(123, 262, 141, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 440, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcmtActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnsinginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinginActionPerformed
        // TODO add your handling code here:
        if(checkDL()){
            String name = txtname.getText();
            String cmt = txtcmt.getText();
            String email = txtemail.getText();
            String pass = txtpass.getText();
            if(pass.equals(txtpass1.getText())){
                Student stu = new Student(name,cmt,email,pass);
                studentService.addStudent(stu);
                LoginStudent loginStudent = new LoginStudent();
                loginStudent.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Mật khẩu không trùng khớp", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }     
    }//GEN-LAST:event_btnsinginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKySV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKySV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKySV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKySV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangKySV dangKySV = new DangKySV(new javax.swing.JFrame(), true);
                dangKySV.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dangKySV.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsingin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jpass;
    private javax.swing.JLabel jpass1;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JTextField txtcmt;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JPasswordField txtpass1;
    // End of variables declaration//GEN-END:variables
    private boolean checkDL() {
        if(!Pattern.matches("^([a-z A-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ])[a-z A-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]+$", txtname.getText())){
            JOptionPane.showMessageDialog(this, "Họ và tên chỉ có chữ cái", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(!Pattern.matches("\\d{12}$", txtcmt.getText())){
            JOptionPane.showMessageDialog(this, "Chứng minh thư chỉ có 12 chữ số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;                 
        }else if(!Pattern.matches("^[a-zA-z0-9_-]+(@gmail.com)$", txtemail.getText())){
            JOptionPane.showMessageDialog(this, "Email có dạng x..x@gmail.com", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;           
        }else if(txtpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mật khẩu", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false; 
        }else return true;
    }
}
