/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import model.Subject;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import service.SubjectService;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author linh
 */

public class HocPhi extends javax.swing.JFrame {
    private SubjectService subjectService;
    private static DefaultTableModel defaultTableModel;
    //private JButton btnXuatfile;
    /**
     * Creates new form HocPhi
     */
    public HocPhi() {
        initComponents();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }            
        };
        subjectService = new SubjectService();
        defaultTableModel = (DefaultTableModel) TableSubject.getModel();     
        setDataTableSubject(subjectService.getAllSubjects());
        setResizable(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbMaNganh = new javax.swing.JComboBox<>();
        txtTongTien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSubject = new javax.swing.JTable();
        btntongtien = new javax.swing.JButton();
        btnXuatfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(530, 440));
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Ngành");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(219, 6, 57, 29);

        cbMaNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNTT", "ATTT", "DT", "DTVT", "CNDPT", "MAR", "QTKD", "KT", "TMDT", " ", " " }));
        cbMaNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaNganhActionPerformed(evt);
            }
        });
        getContentPane().add(cbMaNganh);
        cbMaNganh.setBounds(313, 7, 105, 29);

        txtTongTien.setEditable(false);
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });
        getContentPane().add(txtTongTien);
        txtTongTien.setBounds(210, 310, 291, 30);

        TableSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Môn học", "Tên Môn học", "Số tín chỉ", "Gía tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableSubject);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 42, 490, 260);

        btntongtien.setText("Tổng tiền:");
        btntongtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntongtienActionPerformed(evt);
            }
        });
        getContentPane().add(btntongtien);
        btntongtien.setBounds(108, 313, 100, 23);

        btnXuatfile.setBackground(new java.awt.Color(255, 0, 51));
        btnXuatfile.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatfile.setText("Xuất Fille");
        btnXuatfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatfileMouseClicked(evt);
            }
        });
        btnXuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatfileActionPerformed(evt);
            }
        });
        getContentPane().add(btnXuatfile);
        btnXuatfile.setBounds(220, 350, 83, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -10, 590, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void cbMaNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaNganhActionPerformed
        // TODO add your handling code here:
        String manganh = cbMaNganh.getSelectedItem().toString();
        List<Subject> list = subjectService.getAllSubjects();
        List<Subject> res = new ArrayList<>();
        for(Subject sub:list){
            if(chuanHoaMa(sub.getMa()).equals(manganh) || chuanHoaMa(sub.getMa()).equals("CB")){
                res.add(sub);
            }
        }
        setDataTableSubject(res);
    }//GEN-LAST:event_cbMaNganhActionPerformed

    private void btntongtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntongtienActionPerformed
        // TODO add your handling code here:
        long tongtien = 0;
        String manganh = cbMaNganh.getSelectedItem().toString();
        List<Subject> list = subjectService.getAllSubjects();
        for(Subject sub:list){
            if(chuanHoaMa(sub.getMa()).equals(manganh) || chuanHoaMa(sub.getMa()).equals("CB")){
                tongtien += sub.getGiatien();
            }
        }
        txtTongTien.setText(String.valueOf(tongtien));
    }//GEN-LAST:event_btntongtienActionPerformed
    
    private void btnXuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatfileActionPerformed
        // TODO add your handling code here:
        JFileChooser savefile = new JFileChooser();
        savefile.setSize(500, 400);
        int value = savefile.showSaveDialog(this);
        if(value == JFileChooser.APPROVE_OPTION){
            try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet spreadsheet = workbook.createSheet(cbMaNganh.getSelectedItem().toString());

            XSSFRow row = null;
            Cell cell = null;

            row = spreadsheet.createRow((short) 2);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("DANH SÁCH MÔN HỌC");

            row = spreadsheet.createRow((short) 3);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã môn học");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Tên môn học");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Số tín chỉ");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Giá tiền");
            

            SubjectService subjectService = new SubjectService();

            List<Subject> listItem = subjectService.getAllSubjects();

            for (int i = 0; i < listItem.size(); i++) {
                Subject sub = listItem.get(i);
                row = spreadsheet.createRow((short) 4 + i);
                row.setHeight((short) 400);
                row.createCell(0).setCellValue(i + 1);
                row.createCell(1).setCellValue(sub.getMa());
                row.createCell(2).setCellValue(sub.getTen());
                row.createCell(3).setCellValue(sub.getTinchi());
                row.createCell(4).setCellValue(sub.getGiatien());
            }
            File file = savefile.getSelectedFile();
            System.out.println(file.getPath().toString());
            String s = file.getPath().toString()+".xlsx";
            FileOutputStream out = new FileOutputStream(s);
            workbook.write(out);
            out.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
            //File file = ;
        }
        

    }//GEN-LAST:event_btnXuatfileActionPerformed

    private void btnXuatfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatfileMouseClicked
        // TODO add your handling code here:
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet spreadsheet = workbook.createSheet("Học viên");

            XSSFRow row = null;
            Cell cell = null;

            row = spreadsheet.createRow((short) 2);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("DANH SÁCH MÔN HỌC");

            row = spreadsheet.createRow((short) 3);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã môn học");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Tên môn học");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Số tín chỉ");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Giá tiền");
            

            SubjectService subjectService = new SubjectService();

            List<Subject> listItem = subjectService.getAllSubjects();

            for (int i = 0; i < listItem.size(); i++) {
                Subject sub = listItem.get(i);
                row = spreadsheet.createRow((short) 4 + i);
                row.setHeight((short) 400);
                row.createCell(0).setCellValue(i + 1);
                row.createCell(1).setCellValue(sub.getMa());
                row.createCell(2).setCellValue(sub.getTen());
                row.createCell(3).setCellValue(sub.getTinchi());
                row.createCell(4).setCellValue(sub.getGiatien());
                //row.createCell(5).setCellValue(hocVien.getDia_chi());
            }

            FileOutputStream out = new FileOutputStream(new File("F:/danhsachmonhoc.xlsx"));
            workbook.write(out);
            out.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXuatfileMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HocPhi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HocPhi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HocPhi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HocPhi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HocPhi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableSubject;
    private javax.swing.JButton btnXuatfile;
    private javax.swing.JButton btntongtien;
    private javax.swing.JComboBox<String> cbMaNganh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
    public String chuanHoaMa(String s){
        if(s.substring(0, 4).equals("CNTT")){
            return "CNTT";
        }
        else if(s.substring(0, 4).equals("ATTT")){
            return "ATTT";
        }
        else if(s.substring(0, 2).equals("DT")){
            return "DT";
        }
        else if(s.substring(0, 4).equals("DTVT")){
            return "DTVT";
        }
        else if(s.substring(0, 5).equals("CNDPT")){
            return "CNDPT";
        }
        else if(s.substring(0, 3).equals("MAR")){
            return "MAR";
        }
        else if(s.substring(0, 2).equals("KT")){
            return "KT";
        }
        else if(s.substring(0, 4).equals("QTKD")){
            return "QTKD";
        }
        else if(s.substring(0, 4).equals("TMDT")){
            return "TMDT";
        }
        else{
            return "CB";
        }
    }
    public static void setDataTableSubject(List<Subject> list){
        defaultTableModel.setRowCount(0);
        int stt = 1;
        for(Subject sub:list){
            defaultTableModel.addRow(new Object[]{
                stt,
                sub.getMa(),
                sub.getTen(),
                sub.getTinchi(),
                sub.getGiatien(),    
            });
            stt++;
        }
    }

}
