/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Student;
import service.StudentService;


/**
 *
 * @author Duc Thanh
 */
public class HoSo extends javax.swing.JDialog {
    private StudentService studentService;
    private Student student;
    /**
     * Creates new form EditStudentFormDialog
     */
    public HoSo(java.awt.Frame parent, boolean modal,Student stu) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        this.student = stu;
        studentService = new StudentService();
        txtID.setText(stu.getId());
        txtName.setText(stu.getName());
        txtNgaySinh.setText(stu.getBirthday());
        txtCMT.setText(stu.getCard_number());
        cbGioiTinh.setSelectedIndex(0);
        for(int i = 0 ; i < cbGioiTinh.getItemCount(); i++){
            if(cbGioiTinh.getItemAt(i).equals(stu.getGender())){
                cbGioiTinh.setSelectedIndex(i);
                break;
            }
            
        }
        txtDiemXetTuyen.setText(String.valueOf(stu.getTest_score()));
        txtEmail.setText(stu.getEmail());
        txtDiaChi.setText(stu.getAddress());
        txtSoDienThoai.setText(stu.getPhone_number());
        cbNganhHoc.setSelectedIndex(0);
        for(int i = 0 ; i < cbNganhHoc.getItemCount(); i++){
            if(cbNganhHoc.getItemAt(i).equals(stu.getMajors())){
                cbNganhHoc.setSelectedIndex(i);
                break;
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCMT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbGioiTinh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtDiemXetTuyen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbNganhHoc = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sửa thông tin sinh viên");
        setMinimumSize(new java.awt.Dimension(420, 510));
        getContentPane().setLayout(null);

        jLabel10.setText("ID:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 30, 30, 14);

        txtID.setEditable(false);
        getContentPane().add(txtID);
        txtID.setBounds(90, 20, 300, 30);

        jLabel1.setText("Họ tên:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 70, 50, 14);
        getContentPane().add(txtName);
        txtName.setBounds(90, 60, 300, 30);

        jLabel2.setText("Ngày sinh:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 110, 60, 14);
        getContentPane().add(txtNgaySinh);
        txtNgaySinh.setBounds(90, 100, 300, 30);

        jLabel3.setText("Số CMT/CCCD:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 150, 90, 14);

        txtCMT.setEditable(false);
        getContentPane().add(txtCMT);
        txtCMT.setBounds(90, 140, 298, 30);

        jLabel4.setText("Giới tính:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 190, 42, 14);

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        cbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGioiTinhActionPerformed(evt);
            }
        });
        getContentPane().add(cbGioiTinh);
        cbGioiTinh.setBounds(90, 180, 60, 30);

        jLabel5.setText("Điểm xét tuyển:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 230, 90, 14);
        getContentPane().add(txtDiemXetTuyen);
        txtDiemXetTuyen.setBounds(90, 220, 299, 30);

        jLabel6.setText("Email:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 270, 40, 14);

        txtEmail.setEditable(false);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(90, 260, 300, 30);

        jLabel7.setText("Địa chỉ:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 310, 50, 14);
        getContentPane().add(txtDiaChi);
        txtDiaChi.setBounds(90, 300, 301, 30);

        jLabel8.setText("SĐT:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 350, 40, 14);

        txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiActionPerformed(evt);
            }
        });
        getContentPane().add(txtSoDienThoai);
        txtSoDienThoai.setBounds(90, 340, 300, 30);

        jLabel9.setText("Ngành học:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 390, 60, 14);

        cbNganhHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công Nghệ Thông Tin", "An Toàn Thông Tin", "Công Nghệ Kỹ Thuật Điện-Điện Tử", "Kỹ Thuật Điện Tử Viễn Thông", "Công Nghệ Đa Phương Tiện", "Marketing", "Quản Trị Kinh Doanh", "Kế Toán", " " }));
        getContentPane().add(cbNganhHoc);
        cbNganhHoc.setBounds(90, 380, 298, 30);

        btnSave.setBackground(new java.awt.Color(255, 0, 51));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Cập Nhật");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(305, 439, 88, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add1.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 460, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(checkDL()){
            String id = txtID.getText();
            String name = txtName.getText();
            String ns = txtNgaySinh.getText();
            String cmt = txtCMT.getText();
            String gioiTinh = cbGioiTinh.getSelectedItem().toString();
            Float diemXT = Float.valueOf(txtDiemXetTuyen.getText());
            String email = txtEmail.getText();
            String diaChi = txtDiaChi.getText();
            String sdt = txtSoDienThoai.getText();
            String nganhHoc = cbNganhHoc.getSelectedItem().toString();
            boolean hocBong = false;
            if(diemXT >= 25){
                hocBong = true;
            }
            Student std = new Student(id,name,cmt,ns,gioiTinh,diemXT,email,diaChi,sdt,nganhHoc,hocBong);
            std.setPassword(student.getPassword());
            studentService.editStudent(std);
            this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiActionPerformed

    private void cbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGioiTinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStudentFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStudentFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStudentFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudentFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Student stu = null;
                EditStudentFormDialog dialog = new EditStudentFormDialog(new javax.swing.JFrame(), true,stu);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbNganhHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCMT;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiemXetTuyen;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoDienThoai;
    // End of variables declaration//GEN-END:variables
    private boolean checkDL() {
        if(!Pattern.matches("^([a-z A-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ])[a-z A-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]+$", txtName.getText())){
            JOptionPane.showMessageDialog(this, "Họ và tên chỉ có chữ cái", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(!Pattern.matches("^\\d{4}-((0[1-9]{1})|(1[0-2]{1}))-((0[1-9]{1})|([1-2]{1}[0-9]{1})|(3(0|1)))$", txtNgaySinh.getText())){
            JOptionPane.showMessageDialog(this, "Ngày sinh năm-tháng-ngày (yyyy-mm-dd)", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(!Pattern.matches("\\d{12}$", txtCMT.getText())){
            JOptionPane.showMessageDialog(this, "Chứng minh thư chỉ có 12 chữ số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false; 
        }else if(!Pattern.matches("(^-)*\\d+(.\\d+)*", txtDiemXetTuyen.getText())){
            JOptionPane.showMessageDialog(this, "Điểm xét tuyển sai định dạnh", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;                  
        }else if(!Pattern.matches("^[a-zA-z0-9_-]+(@gmail.com)$", txtEmail.getText())){
            JOptionPane.showMessageDialog(this, "Email có dạng x..x@gmail.com", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(txtDiaChi.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Địa chỉ chưa tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;            
        }else if(!Pattern.matches("^(0)\\d{9}$", txtSoDienThoai.getText())){
            JOptionPane.showMessageDialog(this, "SĐT bắt đầu bằng số 0 và có 10 chữ số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false; 
        }else return true;
    }
}
