/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Student;
import service.StudentService;

/**
 *
 * @author linh
 */
public class LoginStudent extends javax.swing.JFrame {
    private static StudentService studentService;
    /**
     * Creates new form LoginStudent
     */
    public LoginStudent() {
        initComponents();
        studentService = new StudentService();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtemaillogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        btnQuenMatKhau = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập tài khoản");
        setMinimumSize(new java.awt.Dimension(410, 330));
        setName("LoginStudent"); // NOI18N
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Tài khoản");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(163, 19, 59, 34);
        jLabel1.getAccessibleContext().setAccessibleName("TÀI KHOẢN");

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(39, 91, 48, 20);

        txtemaillogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailloginActionPerformed(evt);
            }
        });
        getContentPane().add(txtemaillogin);
        txtemaillogin.setBounds(118, 82, 228, 30);

        jLabel3.setBackground(new java.awt.Color(204, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Mật khẩu:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(39, 137, 54, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setText("Nếu bạn chưa có tài khoản?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(172, 249, 141, 23);

        btnLogin.setBackground(new java.awt.Color(255, 51, 51));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Đăng Nhập");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(156, 176, 87, 30);

        btnDangKy.setBackground(new java.awt.Color(255, 51, 51));
        btnDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKy.setText("Đăng Ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangKy);
        btnDangKy.setBounds(317, 242, 73, 30);

        btnQuenMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        btnQuenMatKhau.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        btnQuenMatKhau.setForeground(new java.awt.Color(0, 0, 204));
        btnQuenMatKhau.setText("Quên Mật Khẩu");
        btnQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMatKhauActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuenMatKhau);
        btnQuenMatKhau.setBounds(10, 242, 107, 30);

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass);
        txtpass.setBounds(118, 125, 228, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 410, 300);

        getAccessibleContext().setAccessibleName("LoginStudent");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailloginActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if(checkDL()){
            String email = txtemaillogin.getText();
            String pass = txtpass.getText();
            if(email.equals("admin@gmail.com")&&pass.equals("admin")){
                TeacherManager quanly = new TeacherManager();
                quanly.setVisible(true);
                quanly.setExtendedState(JFrame.MAXIMIZED_BOTH);
                this.dispose();
            }
            else{
                boolean check = false;
                Student stu = new Student();
                List<Student> list = studentService.getAllStudent();
                for(Student a:list){
                    if(a.getEmail().equals(email)){
                        if(a.getPassword()==null){
                            check = false;
                            break;
                        }
                        if(a.getPassword().equals(pass)){
                            stu = a;
                            check = true;
                            break;
                        }
                        
                    }
                }
                if(check){
                    StudentManager studentManager = new StudentManager(stu);
                    studentManager.setVisible(true);
                    studentManager.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Mật khẩu sai", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
        DangKySV dk = new DangKySV(this, true);
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMatKhauActionPerformed
        // TODO add your handling code here:
        QuenMatKhau quenMatKhau = new QuenMatKhau(this,true);
        quenMatKhau.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuenMatKhauActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnQuenMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtemaillogin;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
    private boolean checkDL(){
        if(!Pattern.matches("^[a-zA-z0-9_-]+(@gmail.com)$", txtemaillogin.getText())){
            JOptionPane.showMessageDialog(this, "Email có dạng x..x@gmail.com", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;           
        }else if(txtpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mật khẩu", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false; 
        }else return true;
    }
}
