/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Student;
import service.StudentService;

/**
 *
 * @author linh
 */
public class QuenMatKhau extends javax.swing.JFrame {
    private StudentService studentService;
    /**
     * Creates new form QuenMatKhau
     */
    public QuenMatKhau(java.awt.Frame parent, boolean modal) {
        super();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        studentService = new StudentService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcmt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jpass = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jpass1 = new javax.swing.JLabel();
        txtpass1 = new javax.swing.JPasswordField();
        btnsingin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 350));
        getContentPane().setLayout(null);

        txtTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(255, 51, 51));
        txtTitle.setText("Nhập thông tin lấy mật khẩu");
        getContentPane().add(txtTitle);
        txtTitle.setBounds(113, 11, 210, 30);

        jLabel1.setText("CMT/CCCD:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 86, 70, 14);

        txtcmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcmtActionPerformed(evt);
            }
        });
        getContentPane().add(txtcmt);
        txtcmt.setBounds(127, 73, 234, 30);

        jLabel2.setText("Email:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 124, 57, 14);

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail);
        txtemail.setBounds(127, 111, 234, 30);

        jpass.setText("Mật khẩu mới:");
        getContentPane().add(jpass);
        jpass.setBounds(10, 162, 85, 14);
        getContentPane().add(txtpass);
        txtpass.setBounds(127, 149, 234, 30);

        jpass1.setText("Nhập lại mật khẩu");
        getContentPane().add(jpass1);
        jpass1.setBounds(10, 200, 100, 14);
        getContentPane().add(txtpass1);
        txtpass1.setBounds(127, 187, 234, 30);

        btnsingin.setBackground(new java.awt.Color(255, 0, 51));
        btnsingin.setForeground(new java.awt.Color(255, 255, 255));
        btnsingin.setText("Lấy lại mật khẩu");
        btnsingin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinginActionPerformed(evt);
            }
        });
        getContentPane().add(btnsingin);
        btnsingin.setBounds(135, 253, 141, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, -10, 450, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcmtActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnsinginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinginActionPerformed
        // TODO add your handling code here:
        if(checkDL()){
            String cmt = txtcmt.getText();
            String email = txtemail.getText();
            String pass = txtpass.getText();
            if(pass.equals(txtpass1.getText())){
                List<Student> list = studentService.getAllStudent();
                Student a = new Student();
                for(Student stu:list){
                    if(stu.getCard_number().equals(cmt) && stu.getEmail().equals(email)){
                        a = stu;
                        break;
                    }
                }
                if(a.isScholarship()){
                    JOptionPane.showMessageDialog(this, "Bạn chưa có tài khoản. Vui lòng đăng ký tài khoản mới", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    a.setPassword(pass);
                    studentService.editStudent(a);
                }
                LoginStudent loginStudent = new LoginStudent();
                loginStudent.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Mật khẩu không trùng khớp", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnsinginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QuenMatKhau().setVisible(true);
//            }
            public void run() {
                QuenMatKhau quenMatKhau = new QuenMatKhau(new javax.swing.JFrame(), true);
                quenMatKhau.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                quenMatKhau.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsingin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jpass;
    private javax.swing.JLabel jpass1;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JTextField txtcmt;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JPasswordField txtpass1;
    // End of variables declaration//GEN-END:variables
    private boolean checkDL() {
        if(!Pattern.matches("\\d{12}$", txtcmt.getText())){
            JOptionPane.showMessageDialog(this, "Chứng minh thư chỉ có 12 chữ số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;                 
        }else if(!Pattern.matches("^[a-zA-z0-9_-]+(@gmail.com)$", txtemail.getText())){
            JOptionPane.showMessageDialog(this, "Email có dạng x..x@gmail.com", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;           
        }else if(txtpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mật khẩu", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false; 
        }else return true;
    }
}
