/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Student;
import service.StudentService;

/**
 *
 * @author linh
 */
public class SuaMatKhau extends javax.swing.JFrame {
    private StudentService studentService;
    /**
     * Creates new form QuenMatKhau
     */
    public SuaMatKhau(java.awt.Frame parent, boolean modal) {
        super();
        initComponents();
        setLocationRelativeTo(null);
        studentService = new StudentService();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpass = new javax.swing.JLabel();
        txtMKmoi = new javax.swing.JPasswordField();
        jpass1 = new javax.swing.JLabel();
        txtMKmoi1 = new javax.swing.JPasswordField();
        btnsuaMK = new javax.swing.JButton();
        txtMKcu = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sửa mật khẩu");
        setMinimumSize(new java.awt.Dimension(420, 350));
        getContentPane().setLayout(null);

        txtTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(255, 51, 51));
        txtTitle.setText("Đổi mật khẩu");
        getContentPane().add(txtTitle);
        txtTitle.setBounds(153, 22, 110, 30);

        jLabel1.setText("Mật khẩu hiện tại:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 89, 90, 14);

        jpass.setText("Mật khẩu mới:");
        getContentPane().add(jpass);
        jpass.setBounds(10, 149, 90, 14);
        getContentPane().add(txtMKmoi);
        txtMKmoi.setBounds(124, 136, 234, 30);

        jpass1.setText("Nhập lại mật khẩu");
        getContentPane().add(jpass1);
        jpass1.setBounds(10, 207, 110, 14);
        getContentPane().add(txtMKmoi1);
        txtMKmoi1.setBounds(124, 194, 234, 30);

        btnsuaMK.setBackground(new java.awt.Color(255, 0, 51));
        btnsuaMK.setForeground(new java.awt.Color(255, 255, 255));
        btnsuaMK.setText("Cập nhật mật khẩu");
        btnsuaMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaMKActionPerformed(evt);
            }
        });
        getContentPane().add(btnsuaMK);
        btnsuaMK.setBounds(135, 253, 141, 30);
        getContentPane().add(txtMKcu);
        txtMKcu.setBounds(124, 76, 234, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, -20, 450, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsuaMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaMKActionPerformed
        // TODO add your handling code here:
        if(checkDL()){
            String MKcu = txtMKcu.getText();
            String MKmoi = txtMKmoi.getText();
            if(MKmoi.equals(txtMKmoi1.getText())){
                List<Student> list = studentService.getAllStudent();
                Student a = new Student();
                boolean check = true;
                for(Student stu:list){
                    if(stu.getPassword()==null) continue;
                    if(stu.getPassword().equals(MKcu)){
                        a = stu;
                        check = false;
                        break;
                    }
                }
                if(check){
                    JOptionPane.showMessageDialog(this, "Mật khẩu hiện tại không đúng. Vui lòng nhập lại mật khẩu hiện tại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    a.setPassword(MKmoi);
                    studentService.editStudent(a);
                    JOptionPane.showMessageDialog(this, "Cập nhật mật khẩu thành công!");
//                    StudentManager studentManager = new StudentManager();
//                    studentManager.setVisible(true);
//                    studentManager.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.dispose();
                }               
            }
            else{
                JOptionPane.showMessageDialog(this, "Mật khẩu không trùng khớp", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnsuaMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QuenMatKhau().setVisible(true);
//            }
            public void run() {
                SuaMatKhau suaMatKhau = new SuaMatKhau(new javax.swing.JFrame(), true);
                suaMatKhau.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                suaMatKhau.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsuaMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jpass;
    private javax.swing.JLabel jpass1;
    private javax.swing.JPasswordField txtMKcu;
    private javax.swing.JPasswordField txtMKmoi;
    private javax.swing.JPasswordField txtMKmoi1;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
    private boolean checkDL() {
        if(txtMKmoi.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mật khẩu", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false; 
        }else return true;
    }
}
