/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import service.IOFile;

/**
 *
 * @author linh
 */
public class TeacherManager extends javax.swing.JFrame {
    private IOFile iOFile;
    /**
     * Creates new form TeacherManager
     */
    public TeacherManager() {
        initComponents();
        iOFile = new IOFile();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQLSinhVien = new javax.swing.JButton();
        btnQLMonHoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textfile = new javax.swing.JTextPane();
        btnDangXuat = new javax.swing.JButton();
        btnxuatthongbao = new javax.swing.JButton();
        btndocfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TeacherManager");
        getContentPane().setLayout(null);

        btnQLSinhVien.setBackground(new java.awt.Color(255, 0, 51));
        btnQLSinhVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLSinhVien.setText("QUẢN LÝ SINH VIÊN");
        btnQLSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSinhVienActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLSinhVien);
        btnQLSinhVien.setBounds(10, 20, 460, 190);

        btnQLMonHoc.setBackground(new java.awt.Color(255, 0, 51));
        btnQLMonHoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLMonHoc.setText("QUẢN LÝ MÔN HỌC");
        btnQLMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLMonHocActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLMonHoc);
        btnQLMonHoc.setBounds(10, 230, 460, 190);

        jScrollPane1.setViewportView(textfile);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(500, 20, 1010, 790);

        btnDangXuat.setBackground(new java.awt.Color(204, 255, 255));
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangXuat);
        btnDangXuat.setBounds(10, 760, 200, 60);

        btnxuatthongbao.setBackground(new java.awt.Color(204, 255, 255));
        btnxuatthongbao.setText("Xuất thông báo");
        btnxuatthongbao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatthongbaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnxuatthongbao);
        btnxuatthongbao.setBounds(10, 440, 460, 60);

        btndocfile.setBackground(new java.awt.Color(204, 255, 255));
        btndocfile.setText("Đọc file");
        btndocfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocfileActionPerformed(evt);
            }
        });
        getContentPane().add(btndocfile);
        btndocfile.setBounds(10, 510, 460, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 30, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSinhVienActionPerformed
        // TODO add your handling code here:
        QuanLySinhVien quanLySinhVien = new QuanLySinhVien();
        quanLySinhVien.setVisible(true);
//        
//        listStudent.setSize(textfile.getWidth(), textfile.getHeight());
        quanLySinhVien.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnQLSinhVienActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đăng xuất");
        System.out.println("option : " + option);            
        if(option == 0) {
            LoginStudent loginStudent = new LoginStudent();
            loginStudent.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnxuatthongbaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatthongbaoActionPerformed
        // TODO add your handling code here:
        String filename = "fileThongBao.txt";
        try {
            iOFile.writeUTF8Text(filename, textfile.getText());
            textfile.setText(" ");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(TeacherManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TeacherManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnxuatthongbaoActionPerformed

    private void btndocfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocfileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        try {
            textfile.setText(iOFile.readUTF8Text(fc.getSelectedFile().getPath()));
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(TeacherManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TeacherManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndocfileActionPerformed

    private void btnQLMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLMonHocActionPerformed
        // TODO add your handling code here:
        QuanLyMonHoc quanLyMonHoc = new QuanLyMonHoc();
        quanLyMonHoc.setVisible(true);
        quanLyMonHoc.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnQLMonHocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TeacherManager teacherManager = new TeacherManager();
                teacherManager.setVisible(true);
                teacherManager.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQLMonHoc;
    private javax.swing.JButton btnQLSinhVien;
    private javax.swing.JButton btndocfile;
    private javax.swing.JButton btnxuatthongbao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textfile;
    // End of variables declaration//GEN-END:variables
}
